//! The registry fixture the web client's tests are built on, checked against
//! what this server actually answers.
//!
//! `crates/teaksta-web/tests/fixtures/activities.json` is a saved `GET
//! /api/activities` reply, and the client's picker and upload tests read the
//! topics, the exercises and the upload capability out of it. A fixture that
//! drifted from the endpoint would have those tests agreeing with a protocol
//! nothing speaks, so it is compared here against a fresh reply and rewritten
//! from one when `TEAKSTA_UPDATE_FIXTURES` is set — the same flow the block
//! fixtures are regenerated by, which is what the README documents.
//!
//! Unlike those, this one needs no models: the registry is read off state
//! built at startup, so the check runs in a plain `cargo test` and a drifted
//! fixture cannot wait for somebody to run the model-gated suite.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use poem::EndpointExt;
use poem::test::TestClient;
use tempfile::TempDir;

use teaksta::context::Config;
use teaksta::server::api::{AppState, routes};

/// Set this to rewrite the fixture from what the server answers, rather than
/// checking it against one.
const UPDATE_ENV: &str = "TEAKSTA_UPDATE_FIXTURES";

const FIXTURE: &str = "crates/teaksta-web/tests/fixtures/activities.json";

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// The deployment the fixture is taken from: the topics compiled into the
/// binary, and a keep directory — so it is a deployment that takes uploads,
/// which is what the client's upload tests are rendered against.
fn deployment(root: &Path) -> Config {
    Config {
        listen: "127.0.0.1:0".to_string(),
        webapp_dist: None,
        topics: None,
        analysis_dir: root.join("analysed"),
        upload_keep_dir: Some(root.join("keep")),
        upload_temp_dir: root.join("temp"),
        trust_proxy: false,
        rate_limit: None,
        max_page_bytes: 5 * 1024 * 1024,
        azure: None,
    }
}

// [spec:teaksta:sem:sme.src.main.java.werti.server.wer-ti-servlet.wer-ti-servlet.activities-fn+2/test]
#[tokio::test]
async fn the_registry_fixture_is_what_the_server_answers() {
    let root = TempDir::new().expect("a deployment root");
    let config = deployment(root.path());
    let state = Arc::new(AppState::new(config).expect("the deployment boots"));
    let client = TestClient::new(routes(&state.config).data(state));

    let response = client.get("/api/activities").send().await;
    response.assert_status_is_ok();
    let answered = response.0.into_body().into_string().await.expect("a body");

    // The bytes the endpoint wrote, saved as they went over the wire: the
    // client parses a reply, so what it is tested against is a reply.
    let at = repository_root().join(FIXTURE);
    if std::env::var(UPDATE_ENV).is_ok() {
        std::fs::write(&at, &answered).expect("the fixture is written");
        return;
    }

    let saved = std::fs::read_to_string(&at).expect("the fixture is saved");
    assert_eq!(
        saved, answered,
        "activities.json is not what the server answers — rerun with {UPDATE_ENV}=1"
    );
}
